### ISSUE TITLE
Multipart upload fails for Azure storage

### ISSUE THREAD

**Issue by ritazh** [andrewgaul/s3proxy#111] opened 2016-01-05 02:13 UTC
This seems to be a recently introduced issue. Multipart upload against Azure used to work with `UploadPartRequest` and `TransferManager`. Now the individual parts seem to be uploaded successfully, but ends with:
`Error Code: 501 Not Implemented` from the SDK and `exceptions from GetContainerACL are parsed by NullOnContainerNotFound` from S3Proxy log.

S3 backend works as expected.

Will go through each commit since a5221f5. Let me know if you are aware of any change that may have caused this.

**Comment by andrewgaul** [comment] 2016-01-05 06:37
Calling `getBlobAccess` in e93529bfebc90acfab422e43ce14755088c7b6d5 introduced this regression.  `AzureBlobStore.getBlobAccess` throws `UnsupportedOperationException` and instead it could return `BlobAccess.PRIVATE` since Azure blobs are always private access.  What do you think and if you agree can you send jclouds a pull request?  Note that we should make the same change `RegionScopedSwiftBlobStore.getBlobAccess`.

**Comment by ritazh** [comment] 2016-01-05 17:36
Thanks for the pointer. That's exactly where this needs to be updated. According to this [reference](https://msdn.microsoft.com/en-us/library/azure/dd179391.aspx), ACL set on the container level determines access of the blobs within the container. Default access for blobs is `private`. When container ACL is set to `blob`, this allows public access of all blobs within the container. I can use [getContainerAccess](https://github.com/jclouds/jclouds/blob/91b202f4ea7728f043987657259ea5115a648bf3/providers/azureblob/src/main/java/org/jclouds/azureblob/blobstore/AzureBlobStore.java#L349) to figure out the right access for blobs based on the container's ACL. What do you think?

**Comment by andrewgaul** [comment] 2016-01-05 19:29
S3 also has container ACLs but setting them does not influence the blob ACLs.  Therefore I do not think jclouds should map Azure container ACLs to blob ACLs.

**Comment by ritazh** [comment] 2016-01-05 19:45
The issue is that I don't think blob access is always `private` for Azure. When container ACL is set to `Blob`, blob access should be `Public_Read`. 

The ACL mechanism is much granular in S3 where you can set custom ACL on each object in a bucket. In Azure storage, it is set at a blob container level. For Azure, by default, the new container is private and you must specify your storage access key to download blobs from this container. If you want to make the files within the container available to everyone, you can set the container to be public using `blob` access type.

**Comment by andrewgaul** [comment] 2016-01-05 20:17
You describe the *effective* ACL of an object, with the container access cascading to the object access, and not the *actual* ACL the object has.  If a user wants the effective ACL they can query both the container and blob ACLs or use an anonymous HEAD request to see if they can read a private blob in a public container.  Providers like GCS and S3 support both container and object ACLs and we do not want to add mappings to them either which would actually make S3Proxy harder to write since we only get the effective and not the actual ACLs.  I also dislike jclouds magically mapping behaviors since other differences can surface, e.g., does the user have the privileges to query container ACLs, differences in eventual consistency between containers and objects.

**Comment by ritazh** [comment] 2016-01-05 20:44
With the proposed solution to have `AzureBlobStore.getBlobAccess` always return `BlobAccess.PRIVATE` and `putBlob` always accepting `BlobAccess.PRIVATE`, if the blob has access that is not `private`, then it will throw `UnsupportedOperationException`. For consistency, we also need to implement `setBlobAccess` to always set access to `BlobAccess.PRIVATE`. That makes this whole thing pretty much a passthru.

**Comment by andrewgaul** [comment] 2016-01-05 21:52
Agree that we could make `setBlobAccess(BlobAccess.PRIVATE)` succeed as we do with `putBlob(container, blob, new PutOptions().setBlobAccess(BlobAccess.PRIVATE))`.  Either way works for me.

**Comment by ritazh** [comment] 2016-01-05 22:40
Actually, `setBlobAccess` should be left alone since there's no `setPublicAccessForBlob` for `AzureBlobClient` and there's no `Set Blob ACL` operation in the [Azure Blob service API](https://msdn.microsoft.com/en-us/library/azure/dd179377.aspx).

**Comment by andrewgaul** [comment] 2016-01-06 02:47
Fixed by jclouds/jclouds@a12ce5a8b7c61dc9b30476fdb82b7ff1f3f3c5bc.

**Closed by andrewgaul** 2016-01-06 02:47 UTC
