### ISSUE TITLE
Too much data after closed with authorization enabled

### ISSUE THREAD

**Issue by marcusvcs** [andrewgaul/s3proxy#204] opened 2017-03-15 20:45 UTC
Hi,

I am trying to integrate S3Proxy with [Signal-Server](https://github.com/WhisperSystems/Signal-Server). 

I am using the following configuration:

```
s3proxy.secure-endpoint=https://0.0.0.0:9000
s3proxy.authorization=aws_v4
s3proxy.identity=accessKey
s3proxy.credential=accessSecret
s3proxy.keystore-path=example.keystore
s3proxy.keystore-password=example
s3proxy.ignore-unknown-headers=true
s3proxy.ignore-unknown-parameters=true
jclouds.provider=filesystem
jclouds.filesystem.basedir=/opt/s3proxy/data
```

And I am getting the following warning when I try to upload a file:

`W 03-15 20:34:06.094 S3Proxy-18 o.e.jetty.http.HttpParser:1329 |::] badMessage: java.lang.IllegalStateException: too much data after closed for HttpChannelOverHttp@5e8e8a05{r=1,c=false,a=IDLE,uri=}`

After this message, the file is not written in the folder.

If I set authorization to none, everything works.

Do you have any idea why is this not working?
Has something to do with JClouds?

**Comment by marcusvcs** [comment] 2017-03-16 13:20
Now I see that I am getting a 403 error because of the credentials.
I am new to S3 and I am clearly misunderstanding the concepts.

The Signal Server asks for an accessKey and an accessSecret, and I thought that is the same thing of s3proxy.identity and s3proxy.credential, so I put the values like that:

```
accessKey: identity
accessSecret: credential
```

This is the url that the Signal is calling:

https://s3proxy/bucket?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20170316T124640Z&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Expires=3599&X-Amz-Credential=accessKey%2F20170316%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=b5eb3ada5b339c40c302a77e72fbef2b2097dd34288d04d104edf8e2b6d36a18

So, where do I get the accessKey and accessSecret values?

Thanks in advance.

**Comment by andrewgaul** [comment] 2017-03-16 19:10
Can you test again with `s3proxy.ignore-unknown-parameters=false`?  Testing will confirm that this is a duplicate of #160.  You can work around this by configuring the Signal signer for V2 authentication.

**Closed** 2017-03-17 02:39 UTC

**Comment by marcusvcs** [comment] 2017-03-17 10:28
Thanks, 

I will test by Monday.
